### ISSUE TITLE
I can see my head and neck

### ISSUE THREAD

**Issue by BAHEK-BOP** [Dryedcoolbro/LethalGym#1]
When I start the game, I see my neck and head, interacting with the wheel of emotions from the TooManyEmotes mod does not play the selected emotion, the game completely breaks down. from the mod, LethalProgression does not allow you to open a menu with character leveling via esc. My head stops and looks only at one point, while I can walk. When using the ALT button on the ReservedItemSlotCore mod, I can turn my head, but it looks very strange. Errors are also written out in the command line when launching the mod. here are all the screenshots and videos
![image (3)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/f17737ab-4414-4be1-9814-53002b3ae451)
![image (4)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/22c63834-9a7e-431e-bfe6-58fb5d766149)
![image (5)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/0570f6f3-b1e3-46b5-b0e2-528b50741332)

Here's a video of how it looks in the game
https://youtu.be/onjY6rvNjAw

**Comment by Dryedcoolbro** [comment]
This may have been fixed, i just released a patch a few hours ago. see if it works

**Comment by BAHEK-BOP** [comment]
> This may have been fixed, i just released a patch a few hours ago. see if it works

Yes, the update fixed this problem, but my logs in the command line are still red
![image](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/876bf2e0-8f45-421c-9c2a-4f80ea62755b)
![image](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/8620078a-7cc5-4fe7-8226-8441fdc93306)
![image](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/fc4b4c9c-d5e7-497a-acd2-93cf67013acf)
![image](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/dfd13cf7-a6e7-4284-b666-3562d7be3c29)


p.s
 I do not know if possible, I try to fix it myself through configs or something else... 

But not everything can be fixed through configs, and to be honest, I just don't like what is on the command line. However, if this is normal, then good

**Comment by Dryedcoolbro** [comment]
yeah sorry, it was used for testing. I will remove in the next update
