### ISSUE TITLE
My barbells are gone

### ISSUE THREAD

**Issue by BAHEK-BOP** [Dryedcoolbro/LethalGym#2]
To be honest, I do not know how this word will be translated correctly in English, I think I have found the correct translation. If not, then I'll throw a second picture of what exactly I meant. 

For any guy or girl who is engaged in sports, pancakes attached to a barbell that you will have to press are of great importance and impressions. Alas, I sipped quite a bit and my pancakes disappeared... And how to swing?

![vHUqvkK3zDo](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/6758e0ce-9d64-40fb-9ea7-1a611f46156c)
![image (6)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/a4ab3fd7-112e-4b96-a4fc-6708c656f1f7)
![image (7)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/e98c865e-2ddc-419a-8734-ad6049ba872b)

**Comment by BAHEK-BOP** [comment]
LOL 
![image (8)](https://github.com/Dryedcoolbro/LethalGym/assets/157053836/4885f810-31e1-4da4-be5e-aa3d2a7e89b3)

I did another approach on the bench press and on the rack... And pancakes appeared

**Comment by Dryedcoolbro** [comment]
after a few reps you will "level up" and you will gain plates
